In [1]:
import torch
import numpy as np
from model_bruno import *
from utils import *
from itertools import compress

In [1]:
import numpy as np

In [3]:
a = np.array([1,3,2,4,5])
a_str = np.array2string(a)

In [9]:
values_str = []
for value in a:
    values_str.append(str(value))

In [10]:
values_str

['1', '3', '2', '4', '5']

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

img = torch.rand((1,3,96,96))
img = img.to(device)

model = AnchorBackbone()
attention = AttentionHead()
clustering = ClusterAttention()
final_model = AttModel()

c:\Users\bfons\anaconda3\envs\torch\Lib\site-packages\torch\nn\modules\lazy.py:181: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [8]:
model = model.to(device)
attention = attention.to(device)
clustering = clustering.to(device)
final_model = final_model.to(device)

In [4]:
a = model(img)

In [5]:
feat,coords = feat_organizer(a)
att, h = attention(feat)
feat_clusters, proj_clusters = cluster_features(h, att, coords, num_clusters=10)

In [23]:
coords[9,:]

tensor([ 8.,  0., 17., 17.])

In [6]:
att_clusters = clustering(feat_clusters)

In [9]:
final_model(img)

(tensor([[-0.0439,  0.0095,  0.0368, -0.0092,  0.0370,  0.0041,  0.0278, -0.0171,
          -0.0287,  0.0588]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([[[0.1020],
          [0.0980],
          [0.0989],
          [0.1020],
          [0.0967],
          [0.1016],
          [0.0992],
          [0.1018],
          [0.0979],
          [0.1020]]], device='cuda:0', grad_fn=<SoftmaxBackward0>),
 tensor([[36.0008, 37.6772, 15.0000, 15.0000],
         [29.4553, 48.3553, 17.0000, 15.0000],
         [36.5936, 33.3076, 15.0000, 17.0000],
         [37.9183, 35.2590, 15.0000, 15.0000],
         [32.0013, 32.0005, 17.0000, 17.0000],
         [44.8902, 35.1294, 15.0000, 15.0000],
         [45.4833, 29.8984, 15.0000, 17.0000],
         [40.0096, 46.9366, 15.0000, 15.0000],
         [32.7313, 37.6101, 17.0000, 15.0000],
         [41.7329, 44.5261, 15.0000, 15.0000]], device='cuda:0',
        grad_fn=<ToCopyBackward0>))