In [1]:
import torch
import numpy as np
from model_bruno import *
from utils import *
from itertools import compress

In [14]:
img = torch.rand((1,3,96,96))
model = AnchorBackbone()
attention = AttentionHead()
clustering = ClusterAttention()
final_model = AttModel()

c:\Users\Bruno\miniconda3\envs\pytorch\Lib\site-packages\torch\nn\modules\lazy.py:181: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [17]:
a = model(img)

In [18]:
feat,coords = feat_organizer(a)
att, h = attention(feat)
feat_clusters, proj_clusters = cluster_features(h, att, coords, num_clusters=10)

In [23]:
coords[9,:]

tensor([ 8.,  0., 17., 17.])

In [6]:
att_clusters = clustering(feat_clusters)

In [3]:
final_model(img)

Full batch converged at iteration 7/100 with center shifts = tensor([0.]).


(tensor([[0.1048, 0.1007, 0.0962, 0.0986, 0.1010, 0.0977, 0.1005, 0.0994, 0.1002,
          0.1010]], grad_fn=<SoftmaxBackward0>),
 tensor([[[0.1004],
          [0.0996],
          [0.1000],
          [0.0995],
          [0.1006],
          [0.1004],
          [0.0997],
          [0.0998],
          [0.1001],
          [0.0998]]], grad_fn=<SoftmaxBackward0>),
 tensor([[37.4742, 37.6154, 15.0000, 15.0000],
         [30.2243, 42.8157, 17.0000, 15.0000],
         [42.1828, 34.1838, 17.0000, 17.0000],
         [34.1328, 36.6230, 17.0000, 15.0000],
         [40.1674, 41.7017, 15.0000, 15.0000],
         [47.9973, 43.2918, 15.0000, 15.0000],
         [30.0968, 29.3327, 17.0000, 17.0000],
         [40.8359, 33.0722, 15.0000, 17.0000],
         [38.2533, 29.7516, 15.0000, 17.0000],
         [30.8549, 35.1416, 17.0000, 17.0000]], grad_fn=<CopySlices>))